name: Rust

on:
  push:
    paths:
      - "Cargo.toml"
      - "src/**"
      - "devices/**"
      - "!**.md"
      - "./.github/workflows/rust.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "Cargo.toml"
      - "src/**"
      - "devices/**"
      - "!**.md"
      - "./.github/workflows/rust.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build (${{ matrix.config.os }})
    strategy:
      matrix:
        config:
          - os: windows-latest
          - os: ubuntu-latest
          - os: macos-latest
    runs-on: ${{ matrix.config.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test
    - name: Run help
      run: cargo run -- --help
    - uses: actions/upload-artifact@v3
      with:
        name: wchisp-${{ matrix.config.os }}
        path: target/debug/wchisp*
